# config.yaml

database:
  host: "localhost"
  port: 3306
  user: "root"
  password: ""
  dbname: "maqhaa_pos"
  debug: true
externalconnection:
  authservice:
    host: localhost:50051
appport: :8011
grpcport: :50052
imagepath: "../../public/images" 
